language: python
dist: ubuntu

services:
  - docker

jobs:
  include:
    - stage: build
      name: "Build Docker image"
      script:
        - sudo apt-get clean
        - sudo rm -rf /var/lib/apt/lists/*
        - sudo rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true
        - sudo rm /var/lib/apt/lists/lock || true
        - sudo apt-get update -y && sudo apt-get install -y apt-utils
        - docker build -t somativa2:latest .

    - stage: test
      name: "Static Application Security Testing (SAST)"
      script:
        - echo "Run SAST here"
        - npm install htmlhint --save-dev
        - htmlhint index.html


    - stage: deploy
      name: "Deploy to Production"
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker push my-registry/somativa2:latest
      if: branch = main

notifications:
  webhooks: https://fathomless-fjord-12345.herokuapp.com/notify
  on_failure: always
  on_success: always
  on_start: always

  telegram:
    secure: "$TELEGRAM_BOT_KEY"
    chat_id: "$TELEGRAM_CHAT_ID"
    template: "$(cat telegram.sh)"
