pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']], 
                    userRemoteConfigs: [[url: 'https://github.com/SEU_USUARIO/NOME_DO_REPOSITORIO.git']]])
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build and Deploy') {
            steps {
                sh 'npm run build'
                sh 'rsync -avz --delete dist/ USUARIO@SERVIDOR:/CAMINHO/DA/PASTA/DE/DESTINO'
            }
        }
    }
}